`timescale 1ns/1ps
`default_nettype none

`include "qmap_defs.svh"

`ifndef TB_GROUP_PARALLEL
`define TB_GROUP_PARALLEL 4
`endif

// End-to-end QMAP-backed Q/K/V projection compute-path test.
//
// The test uses the compact simulation packet generated by:
//
//   conda run -n llm_fpga python Qwen3-0.6B-Base/python_each_module/21_export_qmap_qkv_projection_image.py \
//     --q-rows 4 --k-rows 2 --v-rows 2 \
//     --output artifacts/test_vectors/qwen3_0p6b_qmap_v1/layer0_qkv_projection_sim.qmap.bin \
//     --manifest artifacts/test_vectors/qwen3_0p6b_qmap_v1/layer0_qkv_projection_sim_manifest.json \
//     --sim-hex FPGA_Project/sim/vectors/qmap_qkv_projection_image_words32.hex \
//     --expected-hex FPGA_Project/sim/vectors/qmap_qkv_projection_expected_words32.hex
//
// Run from the repository root:
//
//   iverilog -g2012 -I FPGA_Project/rtl -o FPGA_Project/sim/tb_qmap_qkv_projection_compute_path.vvp \
//     FPGA_Project/sim/tb_qmap_qkv_projection_compute_path.sv \
//     FPGA_Project/rtl/qmap/protocol/qmap_header_reader.sv \
//     FPGA_Project/rtl/qmap/protocol/qmap_descriptor_reader.sv \
//     FPGA_Project/rtl/qmap/protocol/qmap_dot64_reader.sv \
//     FPGA_Project/rtl/qmap/compute/qmap_qkv_projection_compute_path.sv \
//     FPGA_Project/rtl/lib/q4/q4_dot_product_64.sv \
//     FPGA_Project/rtl/lib/q4/q4_gemv_row_1024.sv
//   vvp FPGA_Project/sim/tb_qmap_qkv_projection_compute_path.vvp
//
// Larger or non-Layer0 packets can be selected with:
//   +IMAGE_HEX=... +EXPECTED_HEX=... +IMAGE_WORDS=... +EXPECTED_WORDS=... +QMAP_BASE=0000000410080000

module tb_qmap_qkv_projection_compute_path;

    localparam int ADDR_WIDTH      = 64;
    localparam int MAX_IMAGE_BYTES = 32'h0024_0000;
    localparam int MEM_WORDS       = MAX_IMAGE_BYTES / 4;
    localparam int MAX_EXPECTED_WORDS = 4096;
    localparam int DEFAULT_IMAGE_WORDS = 32'h0000_4000 / 4;
    localparam int DEFAULT_EXPECTED_WORDS = 8;
    localparam int DEFAULT_TIMEOUT_CYCLES = 100000;
    localparam int DESCRIPTOR_WORDS = 32;
    localparam int DESCRIPTOR_TABLE_WORD_OFFSET = 32'h0100 / 4;
    localparam int DESC_BASE_LO_WORD = 8;
    localparam int DESC_BASE_HI_WORD = 9;
    localparam int DESC_DIM0_WORD    = 12;
    localparam int SLOT_Q_OUT        = 8;
    localparam int SLOT_K_OUT        = 9;
    localparam int SLOT_V_OUT        = 10;

    logic clk;
    logic rst_n;
    logic start;
    logic busy;
    logic done;
    logic error;
    logic [31 : 0] rows_done;
    logic signed [55 : 0] last_row_sum_q26;
    logic signed [31 : 0] last_output_q12_12;

    logic mem_rd_req_valid;
    logic mem_rd_req_ready;
    logic [ADDR_WIDTH-1 : 0] mem_rd_req_addr;
    logic [15 : 0] mem_rd_req_len_bytes;
    logic mem_rd_rsp_valid;
    logic mem_rd_rsp_ready;
    logic [31 : 0] mem_rd_rsp_data;
    logic mem_rd_rsp_last;

    logic mem_wr_req_valid;
    logic mem_wr_req_ready;
    logic [ADDR_WIDTH-1 : 0] mem_wr_req_addr;
    logic [15 : 0] mem_wr_req_len_bytes;
    logic [31 : 0] mem_wr_data;
    logic mem_wr_data_valid;
    logic mem_wr_data_ready;
    logic mem_wr_data_last;
    logic mem_wr_done;
    logic mem_wr_error;

    logic [31 : 0] mem [0 : MEM_WORDS-1];
    logic [31 : 0] expected [0 : MAX_EXPECTED_WORDS-1];

    logic active_read;
    logic [31 : 0] read_index;
    logic [31 : 0] beats_remaining;
    logic active_write;
    logic [31 : 0] write_index;

    integer cycle_count;
    integer request_count;
    integer write_count;
    integer mismatch_count;
    integer expected_index;
    integer image_word_count;
    integer expected_word_count;
    integer timeout_cycles;
    integer matrix_slot;
    integer row;
    integer row_count;
    integer output_word_index;
    logic [63 : 0] output_base_addr;
    logic [ADDR_WIDTH-1 : 0] qmap_base_addr;
    reg [8*256-1 : 0] image_hex_path;
    reg [8*256-1 : 0] expected_hex_path;

    qmap_qkv_projection_compute_path #(
        .ADDR_WIDTH(ADDR_WIDTH),
        .GROUP_PARALLEL(`TB_GROUP_PARALLEL)
    ) dut (
        .i_clk(clk),
        .i_rst_n(rst_n),
        .i_start(start),
        .i_qmap_base_addr(qmap_base_addr),
        .o_busy(busy),
        .o_done(done),
        .o_error(error),
        .o_rows_done(rows_done),
        .o_last_row_sum_q26(last_row_sum_q26),
        .o_last_output_q12_12(last_output_q12_12),
        .o_mem_rd_req_valid(mem_rd_req_valid),
        .i_mem_rd_req_ready(mem_rd_req_ready),
        .o_mem_rd_req_addr(mem_rd_req_addr),
        .o_mem_rd_req_len_bytes(mem_rd_req_len_bytes),
        .i_mem_rd_rsp_valid(mem_rd_rsp_valid),
        .o_mem_rd_rsp_ready(mem_rd_rsp_ready),
        .i_mem_rd_rsp_data(mem_rd_rsp_data),
        .i_mem_rd_rsp_last(mem_rd_rsp_last),
        .o_mem_wr_req_valid(mem_wr_req_valid),
        .i_mem_wr_req_ready(mem_wr_req_ready),
        .o_mem_wr_req_addr(mem_wr_req_addr),
        .o_mem_wr_req_len_bytes(mem_wr_req_len_bytes),
        .o_mem_wr_data(mem_wr_data),
        .o_mem_wr_data_valid(mem_wr_data_valid),
        .i_mem_wr_data_ready(mem_wr_data_ready),
        .o_mem_wr_data_last(mem_wr_data_last),
        .i_mem_wr_done(mem_wr_done),
        .i_mem_wr_error(mem_wr_error)
    );

    initial begin
        clk = 1'b0;
        forever #5 clk = ~clk;
    end

    initial begin : load_vectors
        image_hex_path = "FPGA_Project/sim/vectors/qmap_qkv_projection_image_words32.hex";
        expected_hex_path = "FPGA_Project/sim/vectors/qmap_qkv_projection_expected_words32.hex";
        image_word_count = DEFAULT_IMAGE_WORDS;
        expected_word_count = DEFAULT_EXPECTED_WORDS;
        timeout_cycles = DEFAULT_TIMEOUT_CYCLES;
        qmap_base_addr = `QMAP_QKV_BASE_ADDR;

        if (!$value$plusargs("IMAGE_HEX=%s", image_hex_path)) begin
        end
        if (!$value$plusargs("EXPECTED_HEX=%s", expected_hex_path)) begin
        end
        if (!$value$plusargs("IMAGE_WORDS=%d", image_word_count)) begin
        end
        if (!$value$plusargs("EXPECTED_WORDS=%d", expected_word_count)) begin
        end
        if (!$value$plusargs("TIMEOUT_CYCLES=%d", timeout_cycles)) begin
        end
        if (!$value$plusargs("QMAP_BASE=%h", qmap_base_addr)) begin
        end

        if ((image_word_count < 1) || (image_word_count > MEM_WORDS)) begin
            $display("FAIL: IMAGE_WORDS=%0d is outside supported range 1..%0d",
                     image_word_count,
                     MEM_WORDS);
            $finish(1);
        end

        if ((expected_word_count < 1) || (expected_word_count > MAX_EXPECTED_WORDS)) begin
            $display("FAIL: EXPECTED_WORDS=%0d is outside supported range 1..%0d",
                     expected_word_count,
                     MAX_EXPECTED_WORDS);
            $finish(1);
        end

        for (int mem_init_index = 0 ; mem_init_index < MEM_WORDS ; mem_init_index = mem_init_index + 1) begin
            mem[mem_init_index] = 32'd0;
        end
        for (int exp_init_index = 0 ; exp_init_index < MAX_EXPECTED_WORDS ; exp_init_index = exp_init_index + 1) begin
            expected[exp_init_index] = 32'd0;
        end

        $readmemh(image_hex_path, mem, 0, image_word_count - 1);
        $readmemh(expected_hex_path, expected, 0, expected_word_count - 1);
    end

    assign mem_rd_req_ready = !active_read;
    assign mem_rd_rsp_data  = active_read ? mem[read_index] : 32'd0;
    assign mem_rd_rsp_last  = active_read && (beats_remaining == 32'd1);

    always @(posedge clk) begin
        if (!rst_n) begin
            active_read     <= 1'b0;
            read_index      <= 32'd0;
            beats_remaining <= 32'd0;
            mem_rd_rsp_valid <= 1'b0;
            request_count   <= 0;
        end else begin
            if (mem_rd_req_valid && mem_rd_req_ready) begin
                if ((mem_rd_req_addr < qmap_base_addr) ||
                    (((mem_rd_req_addr - qmap_base_addr) >> 2) >= image_word_count)) begin
                    $display("FAIL: read address out of packet range: 0x%016h", mem_rd_req_addr);
                    $finish(1);
                end
                active_read      <= 1'b1;
                read_index       <= (mem_rd_req_addr - qmap_base_addr) >> 2;
                beats_remaining  <= (mem_rd_req_len_bytes + 16'd3) >> 2;
                mem_rd_rsp_valid <= 1'b1;
                request_count    <= request_count + 1;
            end else if (mem_rd_rsp_valid && mem_rd_rsp_ready) begin
                if (beats_remaining == 32'd1) begin
                    active_read      <= 1'b0;
                    mem_rd_rsp_valid <= 1'b0;
                    beats_remaining  <= 32'd0;
                end else begin
                    read_index       <= read_index + 1'b1;
                    beats_remaining  <= beats_remaining - 1'b1;
                end
            end
        end
    end

    assign mem_wr_req_ready   = !active_write;
    assign mem_wr_data_ready  = active_write;
    assign mem_wr_error       = 1'b0;

    always @(posedge clk) begin
        if (!rst_n) begin
            active_write <= 1'b0;
            write_index  <= 32'd0;
            mem_wr_done  <= 1'b0;
            write_count  <= 0;
        end else begin
            mem_wr_done <= 1'b0;

            if (mem_wr_req_valid && mem_wr_req_ready) begin
                if ((mem_wr_req_addr < qmap_base_addr) ||
                    (((mem_wr_req_addr - qmap_base_addr) >> 2) >= image_word_count)) begin
                    $display("FAIL: write address out of packet range: 0x%016h", mem_wr_req_addr);
                    $finish(1);
                end
                active_write <= 1'b1;
                write_index  <= (mem_wr_req_addr - qmap_base_addr) >> 2;
                if (mem_wr_req_len_bytes != 16'd4) begin
                    $display("FAIL: write request length is not one word: %0d", mem_wr_req_len_bytes);
                    $finish(1);
                end
            end

            if (mem_wr_data_valid && mem_wr_data_ready) begin
                if (!mem_wr_data_last) begin
                    $display("FAIL: expected one-word write with last=1");
                    $finish(1);
                end
                mem[write_index] <= mem_wr_data;
                active_write     <= 1'b0;
                mem_wr_done      <= 1'b1;
                write_count      <= write_count + 1;
            end
        end
    end

    function automatic integer descriptor_word_index(input integer slot, input integer word_offset);
        begin
            descriptor_word_index =
                DESCRIPTOR_TABLE_WORD_OFFSET + (slot * DESCRIPTOR_WORDS) + word_offset;
        end
    endfunction

    task automatic check_output_slot(input integer slot);
        begin
            output_base_addr = {
                mem[descriptor_word_index(slot, DESC_BASE_HI_WORD)],
                mem[descriptor_word_index(slot, DESC_BASE_LO_WORD)]
            };
            output_word_index = (output_base_addr - qmap_base_addr) >> 2;
            row_count = mem[descriptor_word_index(slot, DESC_DIM0_WORD)];

            for (row = 0 ; row < row_count ; row = row + 1) begin
                if (mem[output_word_index + row] !== expected[expected_index]) begin
                    $display(
                        "FAIL: output mismatch slot=%0d row=%0d actual=0x%08h expected=0x%08h",
                        slot,
                        row,
                        mem[output_word_index + row],
                        expected[expected_index]
                    );
                    mismatch_count = mismatch_count + 1;
                end
                expected_index = expected_index + 1;
            end
        end
    endtask

    initial begin
        rst_n = 1'b0;
        start = 1'b0;
        cycle_count = 0;
        mismatch_count = 0;
        expected_index = 0;

        repeat (4) @(posedge clk);
        @(negedge clk);
        rst_n = 1'b1;

        @(negedge clk);
        start = 1'b1;
        @(negedge clk);
        start = 1'b0;

        while ((done != 1'b1) && (cycle_count < timeout_cycles)) begin
            @(posedge clk);
            cycle_count++;
        end

        if (done != 1'b1) begin
            $display("FAIL: timed out waiting for qmap_qkv_projection_compute_path after %0d cycles",
                     timeout_cycles);
            $finish(1);
        end

        #1;
        $display("QMAP-backed QKV projection checks");
        $display("  image_hex           = %0s", image_hex_path);
        $display("  expected_hex        = %0s", expected_hex_path);
        $display("  qmap_base           = 0x%016h", qmap_base_addr);
        $display("  image_words         = %0d", image_word_count);
        $display("  expected_words      = %0d", expected_word_count);
        $display("  read requests       = %0d", request_count);
        $display("  writes              = %0d", write_count);
        $display("  rows_done           = %0d", rows_done);
        $display("  last_row_sum_q26    = %0d", last_row_sum_q26);
        $display("  last_output_q12_12  = %0d", last_output_q12_12);
        $display("  error               = %0d", error);

        if (error) begin
            $display("FAIL: qmap_qkv_projection_compute_path reported error");
            $finish(1);
        end

        check_output_slot(SLOT_Q_OUT);
        check_output_slot(SLOT_K_OUT);
        check_output_slot(SLOT_V_OUT);

        if (expected_index != expected_word_count) begin
            $display("FAIL: expected index mismatch actual=%0d expected=%0d", expected_index, expected_word_count);
            mismatch_count = mismatch_count + 1;
        end

        if (rows_done != expected_word_count) begin
            $display("FAIL: rows_done mismatch actual=%0d expected=%0d", rows_done, expected_word_count);
            mismatch_count = mismatch_count + 1;
        end

        if (write_count != expected_word_count) begin
            $display("FAIL: write_count mismatch actual=%0d expected=%0d", write_count, expected_word_count);
            mismatch_count = mismatch_count + 1;
        end

        if (mismatch_count != 0) begin
            $display("FAIL: %0d QKV output mismatch(es)", mismatch_count);
            $finish(1);
        end

        $display("PASS: qmap_qkv_projection_compute_path wrote Q/K/V outputs matching Python Q12.12 golden words.");
        $finish;
    end

endmodule

`default_nettype wire
