/* Generated by web_assets_generator.py. Do not edit. */
/* Source set SHA-256: d2fc8e450bef24abed3e44b3d05402972ff7ac33f813ec8f289abe6725457090 */
#ifndef QWEB_WEB_ASSETS_H
#define QWEB_WEB_ASSETS_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define QWEB_WEB_ASSETS_SCHEMA_VERSION 1u

typedef struct qweb_web_asset {
    const char *path;
    size_t path_length;
    const char *mime_type;
    const char *etag;
    const uint8_t *body;
    size_t body_length;
} qweb_web_asset_t;

extern const qweb_web_asset_t qweb_web_assets[];
extern const size_t qweb_web_asset_count;
extern const char qweb_web_assets_source_sha256[65];

/*
 * Match one origin-form path byte-for-byte. Query strings, fragments,
 * percent-encoded aliases, prefixes, and traversal spellings fail closed.
 */
const qweb_web_asset_t *qweb_web_asset_find(
    const char *path,
    size_t path_length);

#ifdef __cplusplus
}
#endif

#endif /* QWEB_WEB_ASSETS_H */
