`default_nettype none

// AXI4-Lite product wrapper for the one-token accelerator boundary.
//
// This is intentionally thin: axi4lite_to_mmio_regs serializes the AXI4-Lite
// slave protocol into the tiny valid/ready register port, while
// qmap_one_token_mmio_top keeps owning the software-visible register map and the
// compute/memory boundary. Keep this layer policy-free so the same local MMIO
// register block remains easy to unit-test without AXI.
module qmap_one_token_axil_top #(
    parameter int AXI_ADDR_WIDTH   = 12,
    parameter int ADDR_WIDTH       = 64,
    parameter int MEM_DATA_WIDTH   = 32,
    parameter int MAX_LAYERS       = 28,
    parameter int MAX_CONTEXT      = 256,
    parameter int LAYER_INDEX_WIDTH = (MAX_LAYERS <= 1) ? 1 : $clog2(MAX_LAYERS),
    parameter int LAYER_COUNT_WIDTH = (MAX_LAYERS <= 1) ? 1 : $clog2(MAX_LAYERS + 1),
    parameter int POSITION_WIDTH   = (MAX_CONTEXT <= 1) ? 1 : $clog2(MAX_CONTEXT),
    parameter int INPUT_SIZE       = 1024,
    parameter int GROUP_SIZE       = 64,
    parameter int GROUP_COUNT      = INPUT_SIZE / GROUP_SIZE,
    parameter int GROUP_PARALLEL   = 4,
    parameter int ACT_WIDTH        = 24,
    parameter int ACT_FRAC         = 12,
    parameter int WEIGHT_WIDTH     = 4,
    parameter int SCALE_WIDTH      = 16,
    parameter int SCALE_FRAC       = 14,
    parameter int PARTIAL_WIDTH    = ACT_WIDTH + WEIGHT_WIDTH + $clog2(GROUP_SIZE),
    parameter int SCALED_WIDTH     = PARTIAL_WIDTH + SCALE_WIDTH,
    parameter int ROW_ACC_WIDTH    = SCALED_WIDTH + $clog2(GROUP_COUNT) + 2,
    parameter int TAIL_MAX_TILES   = 9496,
    parameter int TAIL_TILE_ROWS   = 16,
    parameter int TOKEN_ID_WIDTH   = 32,
    parameter int SCORE_WIDTH      = ROW_ACC_WIDTH
) (
    input  wire logic                         i_clk,
    input  wire logic                         i_rst_n,

    input  wire logic [AXI_ADDR_WIDTH-1 : 0]  i_s_axi_awaddr,
    input  wire logic [2 : 0]                 i_s_axi_awprot,
    input  wire logic                         i_s_axi_awvalid,
    output logic                              o_s_axi_awready,
    input  wire logic [31 : 0]                i_s_axi_wdata,
    input  wire logic [3 : 0]                 i_s_axi_wstrb,
    input  wire logic                         i_s_axi_wvalid,
    output logic                              o_s_axi_wready,
    output logic [1 : 0]                      o_s_axi_bresp,
    output logic                              o_s_axi_bvalid,
    input  wire logic                         i_s_axi_bready,

    input  wire logic [AXI_ADDR_WIDTH-1 : 0]  i_s_axi_araddr,
    input  wire logic [2 : 0]                 i_s_axi_arprot,
    input  wire logic                         i_s_axi_arvalid,
    output logic                              o_s_axi_arready,
    output logic [31 : 0]                     o_s_axi_rdata,
    output logic [1 : 0]                      o_s_axi_rresp,
    output logic                              o_s_axi_rvalid,
    input  wire logic                         i_s_axi_rready,

    output logic                              o_axil_busy,
    output logic                              o_busy,
    output logic                              o_done,
    output logic                              o_error,
    output logic [7 : 0]                      o_state_debug,
    output logic [7 : 0]                      o_phase_debug,
    output logic                              o_scheduler_done_pulse,
    output logic                              o_tail_start_pulse,
    output logic                              o_tail_done_pulse,
    output logic                              o_tail_active,
    output logic [LAYER_INDEX_WIDTH-1:0]      o_active_layer_index,
    output logic [LAYER_COUNT_WIDTH-1:0]      o_layers_started,
    output logic [LAYER_COUNT_WIDTH-1:0]      o_layers_completed,
    output logic [MAX_LAYERS-1:0]             o_layer_done_mask,
    output logic [MAX_LAYERS-1:0]             o_layer_error_mask,
    output logic [ADDR_WIDTH-1 : 0]           o_last_layer_output_base_addr,
    output logic [1 : 0]                      o_layer0_active_stage_debug,
    output logic [7 : 0]                      o_layer0_state_debug,
    output logic [1 : 0]                      o_layer0_stage_done_mask,
    output logic [1 : 0]                      o_layer0_stage_error_mask,
    output logic [3 : 0]                      o_layer0_full_stage_done_mask,
    output logic [3 : 0]                      o_layer0_full_stage_error_mask,
    output logic [4 : 0]                      o_body_stage_done_mask,
    output logic [4 : 0]                      o_body_stage_error_mask,
    output logic [31 : 0]                     o_scheduler_mem_read_burst_count,
    output logic [31 : 0]                     o_scheduler_mem_read_word_count,
    output logic [31 : 0]                     o_scheduler_mem_write_req_count,
    output logic [31 : 0]                     o_scheduler_mem_write_word_count,
    output logic                              o_tail_error,
    output logic                              o_tail_norm_saturation,
    output logic [ADDR_WIDTH-1 : 0]           o_tail_effective_final_hidden_base_addr,
    output logic [TOKEN_ID_WIDTH-1 : 0]       o_tail_best_token_id,
    output logic signed [ROW_ACC_WIDTH-1 : 0] o_tail_best_score_q26,
    output logic [31 : 0]                     o_tail_tiles_started,
    output logic [31 : 0]                     o_tail_tiles_completed,
    output logic [31 : 0]                     o_tail_norm_cycle_count,
    output logic [31 : 0]                     o_tail_mem_read_burst_count,
    output logic [31 : 0]                     o_tail_mem_read_word_count,
    output logic [31 : 0]                     o_tail_mem_write_word_count,
    output logic [31 : 0]                     o_mem_read_burst_count,
    output logic [31 : 0]                     o_mem_read_word_count,
    output logic [31 : 0]                     o_mem_write_req_count,
    output logic [31 : 0]                     o_mem_write_word_count,

    output logic                              o_mem_rd_req_valid,
    input  wire logic                         i_mem_rd_req_ready,
    output logic [ADDR_WIDTH-1 : 0]           o_mem_rd_req_addr,
    output logic [15 : 0]                     o_mem_rd_req_len_bytes,
    input  wire logic                         i_mem_rd_rsp_valid,
    output logic                              o_mem_rd_rsp_ready,
    input  wire logic [MEM_DATA_WIDTH-1 : 0]  i_mem_rd_rsp_data,
    input  wire logic                         i_mem_rd_rsp_last,

    output logic                              o_mem_wr_req_valid,
    input  wire logic                         i_mem_wr_req_ready,
    output logic [ADDR_WIDTH-1 : 0]           o_mem_wr_req_addr,
    output logic [15 : 0]                     o_mem_wr_req_len_bytes,
    output logic [31 : 0]                     o_mem_wr_data,
    output logic                              o_mem_wr_data_valid,
    input  wire logic                         i_mem_wr_data_ready,
    output logic                              o_mem_wr_data_last,
    input  wire logic                         i_mem_wr_done,
    input  wire logic                         i_mem_wr_error
);

    localparam int REG_ADDR_WIDTH = 12;

    logic reg_wr_valid;
    logic reg_wr_ready;
    logic reg_rd_valid;
    logic reg_rd_ready;
    logic [REG_ADDR_WIDTH-1 : 0] reg_addr;
    logic [31 : 0] reg_wdata;
    logic [31 : 0] reg_rdata;
    logic reg_error;

    axi4lite_to_mmio_regs #(
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
        .REG_ADDR_WIDTH(REG_ADDR_WIDTH)
    ) axil_adapter (
        .i_clk(i_clk),
        .i_rst_n(i_rst_n),
        .i_s_axi_awaddr(i_s_axi_awaddr),
        .i_s_axi_awprot(i_s_axi_awprot),
        .i_s_axi_awvalid(i_s_axi_awvalid),
        .o_s_axi_awready(o_s_axi_awready),
        .i_s_axi_wdata(i_s_axi_wdata),
        .i_s_axi_wstrb(i_s_axi_wstrb),
        .i_s_axi_wvalid(i_s_axi_wvalid),
        .o_s_axi_wready(o_s_axi_wready),
        .o_s_axi_bresp(o_s_axi_bresp),
        .o_s_axi_bvalid(o_s_axi_bvalid),
        .i_s_axi_bready(i_s_axi_bready),
        .i_s_axi_araddr(i_s_axi_araddr),
        .i_s_axi_arprot(i_s_axi_arprot),
        .i_s_axi_arvalid(i_s_axi_arvalid),
        .o_s_axi_arready(o_s_axi_arready),
        .o_s_axi_rdata(o_s_axi_rdata),
        .o_s_axi_rresp(o_s_axi_rresp),
        .o_s_axi_rvalid(o_s_axi_rvalid),
        .i_s_axi_rready(i_s_axi_rready),
        .o_reg_wr_valid(reg_wr_valid),
        .i_reg_wr_ready(reg_wr_ready),
        .o_reg_rd_valid(reg_rd_valid),
        .i_reg_rd_ready(reg_rd_ready),
        .o_reg_addr(reg_addr),
        .o_reg_wdata(reg_wdata),
        .i_reg_rdata(reg_rdata),
        .i_reg_error(reg_error),
        .o_busy(o_axil_busy)
    );

    qmap_one_token_mmio_top #(
        .ADDR_WIDTH        (ADDR_WIDTH),
        .MEM_DATA_WIDTH    (MEM_DATA_WIDTH),
        .MAX_LAYERS        (MAX_LAYERS),
        .MAX_CONTEXT       (MAX_CONTEXT),
        .LAYER_INDEX_WIDTH (LAYER_INDEX_WIDTH),
        .LAYER_COUNT_WIDTH (LAYER_COUNT_WIDTH),
        .POSITION_WIDTH    (POSITION_WIDTH),
        .INPUT_SIZE        (INPUT_SIZE),
        .GROUP_SIZE        (GROUP_SIZE),
        .GROUP_COUNT       (GROUP_COUNT),
        .GROUP_PARALLEL    (GROUP_PARALLEL),
        .ACT_WIDTH         (ACT_WIDTH),
        .ACT_FRAC          (ACT_FRAC),
        .WEIGHT_WIDTH      (WEIGHT_WIDTH),
        .SCALE_WIDTH       (SCALE_WIDTH),
        .SCALE_FRAC        (SCALE_FRAC),
        .PARTIAL_WIDTH     (PARTIAL_WIDTH),
        .SCALED_WIDTH      (SCALED_WIDTH),
        .ROW_ACC_WIDTH     (ROW_ACC_WIDTH),
        .TAIL_MAX_TILES    (TAIL_MAX_TILES),
        .TAIL_TILE_ROWS    (TAIL_TILE_ROWS),
        .TOKEN_ID_WIDTH    (TOKEN_ID_WIDTH),
        .SCORE_WIDTH       (SCORE_WIDTH)
    ) mmio_top (
        .i_clk(i_clk),
        .i_rst_n(i_rst_n),
        .i_reg_wr_valid(reg_wr_valid),
        .o_reg_wr_ready(reg_wr_ready),
        .i_reg_rd_valid(reg_rd_valid),
        .o_reg_rd_ready(reg_rd_ready),
        .i_reg_addr(reg_addr),
        .i_reg_wdata(reg_wdata),
        .o_reg_rdata(reg_rdata),
        .o_reg_error(reg_error),
        .o_busy(o_busy),
        .o_done(o_done),
        .o_error(o_error),
        .o_state_debug(o_state_debug),
        .o_phase_debug(o_phase_debug),
        .o_scheduler_done_pulse(o_scheduler_done_pulse),
        .o_tail_start_pulse(o_tail_start_pulse),
        .o_tail_done_pulse(o_tail_done_pulse),
        .o_tail_active(o_tail_active),
        .o_active_layer_index(o_active_layer_index),
        .o_layers_started(o_layers_started),
        .o_layers_completed(o_layers_completed),
        .o_layer_done_mask(o_layer_done_mask),
        .o_layer_error_mask(o_layer_error_mask),
        .o_last_layer_output_base_addr(o_last_layer_output_base_addr),
        .o_layer0_active_stage_debug(o_layer0_active_stage_debug),
        .o_layer0_state_debug(o_layer0_state_debug),
        .o_layer0_stage_done_mask(o_layer0_stage_done_mask),
        .o_layer0_stage_error_mask(o_layer0_stage_error_mask),
        .o_layer0_full_stage_done_mask(o_layer0_full_stage_done_mask),
        .o_layer0_full_stage_error_mask(o_layer0_full_stage_error_mask),
        .o_body_stage_done_mask(o_body_stage_done_mask),
        .o_body_stage_error_mask(o_body_stage_error_mask),
        .o_scheduler_mem_read_burst_count(o_scheduler_mem_read_burst_count),
        .o_scheduler_mem_read_word_count(o_scheduler_mem_read_word_count),
        .o_scheduler_mem_write_req_count(o_scheduler_mem_write_req_count),
        .o_scheduler_mem_write_word_count(o_scheduler_mem_write_word_count),
        .o_tail_error(o_tail_error),
        .o_tail_norm_saturation(o_tail_norm_saturation),
        .o_tail_effective_final_hidden_base_addr(o_tail_effective_final_hidden_base_addr),
        .o_tail_best_token_id(o_tail_best_token_id),
        .o_tail_best_score_q26(o_tail_best_score_q26),
        .o_tail_tiles_started(o_tail_tiles_started),
        .o_tail_tiles_completed(o_tail_tiles_completed),
        .o_tail_norm_cycle_count(o_tail_norm_cycle_count),
        .o_tail_mem_read_burst_count(o_tail_mem_read_burst_count),
        .o_tail_mem_read_word_count(o_tail_mem_read_word_count),
        .o_tail_mem_write_word_count(o_tail_mem_write_word_count),
        .o_mem_read_burst_count(o_mem_read_burst_count),
        .o_mem_read_word_count(o_mem_read_word_count),
        .o_mem_write_req_count(o_mem_write_req_count),
        .o_mem_write_word_count(o_mem_write_word_count),
        .o_mem_rd_req_valid(o_mem_rd_req_valid),
        .i_mem_rd_req_ready(i_mem_rd_req_ready),
        .o_mem_rd_req_addr(o_mem_rd_req_addr),
        .o_mem_rd_req_len_bytes(o_mem_rd_req_len_bytes),
        .i_mem_rd_rsp_valid(i_mem_rd_rsp_valid),
        .o_mem_rd_rsp_ready(o_mem_rd_rsp_ready),
        .i_mem_rd_rsp_data(i_mem_rd_rsp_data),
        .i_mem_rd_rsp_last(i_mem_rd_rsp_last),
        .o_mem_wr_req_valid(o_mem_wr_req_valid),
        .i_mem_wr_req_ready(i_mem_wr_req_ready),
        .o_mem_wr_req_addr(o_mem_wr_req_addr),
        .o_mem_wr_req_len_bytes(o_mem_wr_req_len_bytes),
        .o_mem_wr_data(o_mem_wr_data),
        .o_mem_wr_data_valid(o_mem_wr_data_valid),
        .i_mem_wr_data_ready(i_mem_wr_data_ready),
        .o_mem_wr_data_last(o_mem_wr_data_last),
        .i_mem_wr_done(i_mem_wr_done),
        .i_mem_wr_error(i_mem_wr_error)
    );

endmodule

`default_nettype wire
